name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/devcontainer:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - name: test_w32
        run: |
          cmake . --preset w32
          cmake --build build_w32 -t tb
          ctest --test-dir build_w32